
import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react"
import { Content } from "~/components/content";
import { Layout } from "~/components/layout/layout";

const Home: NextPage = () => {

  const { data: sessionData, status } = useSession()

  if (status === "loading") {
    return (
      <Layout>
        <div className="flex items-center justify-center w-full h-[calc(100vh-6rem)]">
          <div className="loading loading-bars loading-lg" />
        </div>
      </Layout>
    )
  }

  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          {sessionData?.user ?
            <Content />
            :
            <div className="flex items-center justify-center h-[calc(100vh-6rem)]">
              <button
                className="btn-primary btn-lg rounded-btn btn"
                onClick={() => void signIn()}
              >
                Sign in
              </button>
            </div>
          }
        </Layout>
      </main>
    </>
  );
};

export default Home;

