import { type Topic } from "@prisma/client";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Header } from "~/components/header";
import { NoteCard } from "~/components/note-card";
import { NoteEditor } from "~/components/note-editor";
import { api } from "~/utils/api";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

export const Content = () => {

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null)

  const { data: sessionData } = useSession()

  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
    }
  );

  useEffect(() => {
    if (topics !== undefined) {
      setSelectedTopic(selectedTopic ?? topics[0] ?? null)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [topics])

  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refetchTopics()
    }
  })

  const { data: notes, refetch: refetchNotes } = api.note.getAll.useQuery(
    {
      topicId: selectedTopic?.id ?? ""
    },
    {
      enabled: sessionData?.user !== undefined && selectedTopic !== null
    }
  )

  const createNote = api.note.create.useMutation({
    onSuccess: () => {
      void refetchNotes();
    }
  })
  const deleteNote = api.note.delete.useMutation({
    onSuccess: () => {
      void refetchNotes();
    }
  })

  return (
    <div className="grid grid-cols-4 gap-2 px-5 pt-5">
      <div className="px-2">
        <ul className="w-full p-2 menu rounded-box bg-base-100">
          {topics?.map((topic) => (
            <li key={topic.id}>
              <Link
                href={'#'}
                onClick={(e) => {
                  e.preventDefault()
                  setSelectedTopic(topic)
                }}
              >
                {topic.title}
              </Link>
            </li>
          ))}
        </ul>
        <div className="divider"></div>
        <input
          type="text"
          placeholder="New topic"
          className="w-full input-bordered input input-sm"
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              createTopic.mutate({
                title: e.currentTarget.value
              })
              e.currentTarget.value = ""
            }
          }}
        />
      </div>
      <div className="col-span-3">
        <p>{selectedTopic?.title}</p>
        <div>
          {notes?.map((note) => (
            <div key={note.id} className="mt-5">
              <NoteCard
                note={note}
                onDelete={() => void deleteNote.mutate({ id: note.id })}
              />
            </div>
          ))}
        </div>
        <NoteEditor
          onSave={({ title, content }) => {
            void createNote.mutate({
              title,
              content,
              topicId: selectedTopic?.id ?? ""
            })
          }}
        />
      </div>
    </div>
  )
}